server:
  port: 60003
info:
  spring-cloud-test:
    description: monitor
    url: https://github.com/jixuju/spring-cloud-test
    build-by: superwind20
endpoints:
  sensitive: false
security:
  user:
    name: user
    password: 123456
spring:
  boot:
    admin:
      context-path: /admin